image: node:16.14.0

cache:
  paths:
    - node_modules/

stages:
  #- test
  - build 
  - deploy

before_script:
  - echo -n ${CI_REGISTRY_TOKEN}
  - docker login -u "${CI_REGISTRY_USER}" -p ${CI_REGISTRY_TOKEN} ${CI_REGISTRY}
  - 'docker stop $(docker ps --filter ancestor=mobilityrentals6/s6-mr-frontend -aq) || echo true'
  - 'docker container rm $(docker ps --filter ancestor=mobilityrentals6/s6-mr-frontend -aq) || echo true'
  - 'docker image prune -f'

#test:
#  stage: test
#  script:
#    - echo "Start building App"
#    - docker build --target test --tag test .
#    - docker rmi test
#  only:
#    - master
#    - production

    
build:
  stage: build
  script: 
    - 'echo ${CI_REGISTRY_IMAGE}:$CI_COMMIT_SHA'
    - 'docker build --tag "${CI_REGISTRY_IMAGE}:latest" --tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} .'
    - 'docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}'
    - 'docker push ${CI_REGISTRY_IMAGE}:latest'
    - 'docker rmi ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}'

  only:
    - production

deploy:
  stage: deploy
  script:
    - 'docker pull ${CI_REGISTRY_IMAGE}:latest'
    - 'docker run -d -p 80:80 ${CI_REGISTRY_IMAGE}:latest'

  only:
    - production
